export const FILE_EXTENSION_TO_LANGUAGE: Readonly<Record<string, string>> = {
  ts: "typescript",
  tsx: "typescript",
  js: "javascript",
  jsx: "javascript",
  json: "json",
  html: "html",
  css: "css",
  scss: "scss",
  md: "markdown",
  yaml: "yaml",
  yml: "yaml",
  py: "python",
  go: "go",
  rs: "rust",
  java: "java",
  cpp: "cpp",
  c: "c",
  sh: "shell",
  default: "plaintext",
};
